spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lulu_oa?nullCatalogMeansCurrent=true
    username: root
    password: sunhao123
    driver-class-name: com.mysql.cj.jdbc.Driver
camunda:
  bpm:
    history-level: audit
server:
  port: 9902
