spring:
  redis:
    host: redis
    port: 6379
    password: sunhao123
  datasource:
    url: jdbc:mysql://db:3306/camunda_demo?nullCatalogMeansCurrent=true
    username: root
    password: sunhao123
    driver-class-name: com.mysql.cj.jdbc.Driver

